export const DOCK_HORIZONTAL_INSET = 16;
export const DOCK_COMPOSITE_HEIGHT = 82;
export const DOCK_BASE_TOP = 12;
export const DOCK_BASE_BOTTOM = 76;
export const DOCK_CHAMBER_SIZE = 60;
export const DOCK_CHAMBER_CENTER_Y = 43;
export const DOCK_CHAMBER_CENTER_FROM_SAFE_BOTTOM =
  DOCK_COMPOSITE_HEIGHT - DOCK_CHAMBER_CENTER_Y;
export const DOCK_MIN_SAFE_BOTTOM = 8;
export const DOCK_CONTENT_CLEARANCE = 18;
export const DOCK_CONTENT_BOTTOM =
  DOCK_COMPOSITE_HEIGHT + DOCK_CONTENT_CLEARANCE;
export const DOCK_LAYER = 20;
